---
abstract: 'Obtain uploaded CPAN modules via RSS.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-SmokeBox-Uploads-RSS
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  POE::Component::SmokeBox::Uploads::RSS:
    file: lib/POE/Component/SmokeBox/Uploads/RSS.pm
    version: 1.00
requires:
  HTML::LinkExtor: 0
  HTTP::Request: 0
  POE: 0.38
  POE::Component::Client::HTTP: 0.82
  POE::Component::RSSAggregator: 1.02
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/poe-component-smokebox-uploads-rss/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-component-smokebox-uploads-rss.git
version: 1.00
